# Generated by Django 4.1.4 on 2023-07-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_director_tag_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='director',
            new_name='directors',
        ),
    ]
