# Generated by Django 4.2.3 on 2023-07-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='directors',
            field=models.ManyToManyField(to='blog.director', verbose_name='Режисcеры'),
        ),
        migrations.AlterModelTable(
            name='director',
            table='directors',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
