# Generated by Django 4.2.3 on 2023-07-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
    ]
