# Generated by Django 4.0 on 2023-07-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_directors_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='directors',
            field=models.ManyToManyField(related_name='posts_director', to='blog.Director', verbose_name='Режисcеры'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts_tag', to='blog.Tag', verbose_name='Теги'),
        ),
    ]
